### PR TITLE
A few fixes

### PR DESCRIPTION
**Pull request by rvs**
Here's a few fixes that I made while making EVE talk to Adam:
   * Go 1.12 mod support
   * Accepting empty messages with something less than 500 InternalServer error
   * Replacing 201 status with 200

The last one is interesting because strictly speaking I don't think controller should reply with 201 unless it is also replying with an URI of a newly created entity (which we are not).

### CODE REVIEW

**Comment by deitch** [comment]
All of these are great, except for the `200` instead of `201`. If we read the API spec for [info](https://github.com/lf-edge/eve/blob/master/api/API.md#info), [metrics](https://github.com/lf-edge/eve/blob/master/api/API.md#metrics), etc., and especially a `/register`, it says that a `POST` of those should return a `201`, not a `200`. This makes sense, since a RESTful API should return `201` for `POST`s that create things. We are adding new log messages or info messages, or registering a new device, not modifying an existing one (`PUT` or `PATCH`, which would return a `200`), or just retrieving a config (`GET`, also `200`).

Let me propose the following: let's split this PR into 2:

* remove the `201`->`200` change, and put it in a separate PR, where we can discuss it
* leave the other changes in here and we can merge them right in

That way we aren't holding this up for the `200`/`201` discussion. How does that sound?

**Comment by rvs** [comment]
Great point on what the spec says, but arguably this could be a question of whether the spec is right or not. In all my experience (which is admittedly not that vast) of designing APIs, the difference between 200 and 201 has always been that 201 is also expected to return a URI of the new thing created. If there's not distinct URI (and the thing was just some internal state mutation) the API should return 200. In our case, I don't think our controllers ever return that URI (be it Adam or zedcloud).

Here's an authoritative resource on this: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

Btw, given that this is RFC coming from IETF I'm sure @eriknordmark may have a thing or two to say here (or at leas he can find somebody who can settle this). I can ask Roy Fielding (the REST guy) if needed.

**Comment by deitch** [comment]
> this could be a question of whether the spec is right or not. 

Indeed. That is a good conversation to have. I just re-read the spec on return codes (thanks for linking to it), and it can go either way. A `POST` can return a `200` or a `201` on success (or a `202` if accepted but not yet created, but that is not relevant here). The way I read it - and the way I think most people in the communities (if such a thing exists) interpret it is:

* `200`: for `POST` to an existing resource (which is not RESTful, but also does not violate the RFC, since REST is layered on top of the RFC)
* `201` for `POST` to create a new resource

We are a bit in no-man's-land, in that we _are_ creating something new, but _are not_ expecting a return, to to be able to access it (at least via the device API). My read is that it fits clearly within the "creating new resource", even if we do not intend to access it. The resource is a new instance of "log" or "info" to "device".

FYI, not trying to nitpick. We are setting a spec here; we should get it as correct as possible so others can build on it.

I can almost guess what Roy would say here: `201` for all of this, but what are we doing with a `/register` endpoint? REST endpoints _always_ are resources. We can `POST /device` or even (weakly) `POST /registration`, but `POST /register`?!?

More than happy to bring him in. I would like to see what he says.

**Comment by rvs** [comment]
As it happens @eriknordmark pointed out that if we want to be really pedantic, we should probably use 204 anyway https://tools.ietf.org/html/rfc7231#page-53

Thoughts @deitch ?

**Comment by rvs** [comment]
Also, @deitch let me split this PR so we can proceed with the rest of the fixes.

**Comment by rvs** [comment]
Hey @deitch can you please review just this portion -- the 20X discussion commit is coming separately.

**Comment by deitch** [comment]
> if we want to be really pedantic, we should probably use 204 anyway 

I think he may be right (which is my way of saying, "of course Erik makes sense here!"). I am not sure I have seen it used heavily in the wild, though. Usually it is "create a new resource gets a `201`", but each of us has our own separate experiences.

To get _really_ pedantic, we should:

* `POST /devices`, not `POST /register` (resource, not action)
* return `201` with a link to the newly registered device `/devices/<uuid>`
* have all other actions `POST /devices/<uuid>/info` or `GET /devices/<uuid>/config`, etc.

We still use the onboard+serial (for `POST /devices`) or device cert (for all others) to authenticate, but the URI is unique.
I am more than willing to go down that path. We can fix adam easily, EVE with a bit more effort but not terrible. Not sure about Zedcloud.

I _do_ prefer to get it right day 1, but won't be too pedantic about it. 

The one thing I am sure about, is that if we decide to do this 100% restful and correct, let's get it now. It only will get harder by day going forward.

**Comment by deitch** [comment]
I am going to open a new issue for the `200` vs `201` return codes. Let us move it all to there.

**Comment by deitch** [comment]
Everything moved over to #5. I think I got all of the comments. If I missed any, please cut-and-paste. Going to close this conversation to ensure it moves there.

**Pull request merged**
